name: Cypress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
          
    - name: Install NPM
      run: npm install

    - name: Install dependencies
      run:
          npm install cypress
      

    - name: Execute test
      run:
          npx cypress run 
