name: Cypress

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
          
    - name: Install NPM
      run: npm install

    - name: Install dependencies
      run:
          npm install cypress
      

    - name: Execute test
      run:
          npx cypress run 
